### ISSUE TITLE
TypeError undefined property

### ISSUE THREAD

**Issue by sayed-k-ali** [khairulazman67/Back-End-IoT-Aquaculture-Monitoring-#1]
https://github.com/khairulazman67/Back-End-IoT-Aquaculture-Monitoring-/blob/be0759904530d0ac2b19d161010c0c710c2571d0/mqtt/pub.js#L63

To prevent this issue, you can try fix by this way:

`var pH_min_limits = response.data.data[0]? response.data.data[0].min_limit: 0`

**Comment by khairulazman67** [comment]
Thank you for participating, I have fixed the issue
